baseurl: https://shitao5.org/
languageCode: zh-CN
title: "Shitao Wu | 吴诗涛"
theme: paged
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
features: ["blog"]
googleAnalytics: "G-TKPT8Q5NBV"

permalinks:
  post: /:year/:month/:slug/

outputs:
  home: [html, rss, json]

author:
  name: "吴诗涛"

menu:
  main:
    - name: 首页
      url: "/"
      weight: 1
    - name: 关于
      url: "/about/"
      weight: 2
    - name: ️日志
      url: "/posts/"
      weight: 3
    - name: 总结
      url: "/summary/"
      weight: 5
    - name: 此刻
      url: "/moments/"
      weight: 4
    - name: 书摘
      url: "/excerpt/"
      weight: 6
    - name: 搜索
      url: "/search/"
      weight: 7
    # - name: 👋对话
    #   url: "/chat/"
    #   weight: 8
    - name: 🎯订阅
      url: "/index.xml"
      weight: 9

params:
  description: "吴诗涛的个人博客，记录工作实践、思考沉淀、技术探索与生活随笔。"
  footer: "&copy; [Shitao Wu](/) 2019 - {Year}"
  logo:
    en:
      alt: 修狗
      img: "logo.png"
  customJS:
    - "comment-utils.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
  githubContentURL: "https://github.com/Shitao5/shitao-blog/edit/main/content/"

  lang:
    edit:
      en: "编辑"
    license:
      en: "版权"
    search:
      en: "搜索"
    top:
      cn: "登顶"

markup:
  highlight:
    codeFences: true
    style: "github"
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
