[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.99.1'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
command = 'hugo --buildFuture'
[context.production.environment]
HUGO_ENV = 'production'
TZ="/usr/share/zoneinfo/Asia/Bangkok"
