---
title: '2026 年周总结'
author: 吴诗涛
date: '2026-01-01'
slug: 2026
---

<br>

::: fullwidth
```{r message=FALSE, warning=FALSE, out.width="100%", echo=FALSE}
# 根据2026年运动记录表作图
record = read.csv("sport.csv")
record$日期 = as.Date(record$日期, format = "%Y-%m-%d")

today = ifelse(Sys.Date() >= "2026-01-14", Sys.Date(), "2026-01-14") |> as.Date()

library(echarts4r)

record |>
  e_charts(日期) |>
  e_line(骑行, name = "骑行️🚴", y_index = 0) |>
  e_line(跑步, name = "跑步🏃", y_index = 0) |>
  e_bar(跳绳, name = "跳绳🪢", y_index = 1) |>
  e_x_axis(type = "category", axisLabel = list(formatter = htmlwidgets::JS("function(value, index) {
    var date = echarts.format.formatTime('MM-dd', new Date(value));
    var dayOfWeek = ['日', '一', '二', '三', '四', '五', '六'][new Date(value).getDay()];
    return date + '\\n周' + dayOfWeek;
  }"))) |>
  e_y_axis(index = 0, name = "公里数") |>
  e_y_axis(index = 1, name = "个数") |>
  e_datazoom(startValue = today - 12, endValue = today + 1, toolbox = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_mark_point("骑行️🚴", data = list(type = "max")) |>
  e_mark_point("跑步🏃", data = list(type = "max")) |>
  e_mark_point("跳绳🪢", data = list(type = "max")) |>
  e_title("运动情况", "每周日更新") |>
  e_toolbox_feature("restore") |>
  e_toolbox_feature("saveAsImage") |>
  e_grid(top = '17%') |>
  e_legend(top = "3%") |>
  e_color(c("#B80000", "#5F8670", "#FF9800"))
```
:::

# 第 01 周（1229-0104）

这么快又新建文件写新一年的总结了。不过今年这个文件是直接让 Codex 参考往年文件生成的，这两年人工智能的发展真是快，不知道今年这个文件里边，又会记录多少让我惊喜的事情。

本周作为公司文化大使，审批了全员的文化积分，是我任期最后的大任务啦，明年就交给下一任文化大使咯！

周三（1231）是公司战略誓师会和年会，是战略研讨会一个非常重要的节点。我也上台代表总经办讲解 2026 年部门目标，然后带着我的小伙伴一起宣誓。今年年会俺没喝酒，中了三等奖（大疆 Action 4），还没捂热第二天就被小王闲鱼出手了，因为我已经有一个 Insta Go 3s 啦！

元旦假期做城市跨越者，1号睡个懒觉，送小王回安吉，吃晚饭后回桐乡；2号家里蹲，美滋滋；3号吃完午饭去安吉，吃完晚饭带小王回杭州，两天多不在杭州，王建国快把家拆完了。3号去安吉，带了好多老爸种的菜，老爸今年精细化耕作，大丰收，萝卜比梨都甜，小王麻麻喊来她的小姐妹分了分，都赞不绝口。

周日（0104）上班，又是总结又是绩效，还有一堆活，忙坏了。2026 年要缩短加班时间，回归生活，包括恢复运动，加油加油！

# 第 02 周（0105-0111）

本周开始恢复运动，虽进度慢，但好在是开始了。减少的加班时间，除了运动，便是在家跟进 AI 前沿的内容。

周五（0109）开小白带上老板和财务总去出差，晚上饱餐一顿才回杭。周六（0110）和小王回学校理发，绕着学校开了一圈。

另外，今年起也多写多记录，哪怕只是短短几十字也好。将每周的想法记录到日志中去，而不是散落在每周的总结这边。

# 第 03 周（0112-0118）

这周骑行上下班坚持的还不错，周一（0112）因为背包太重便开驴驴去。周二（0113）请假办签证去啦！

因人力同事休产假，承接了她股权事项的工作，恰又逢持股平台变更，真是事情多多。好在有先见之明开发了 Word 模版批量填充的[工具](https://wantme.chat/)才在这周完成了大部分签署工作。话说回来这个工具我准备写个小文章还没来得及。

周五（0116）晚上和小王回安吉，周末两天陈兄培训，看他黑眼圈有点重，提醒他注意休息，好好睡觉别想太多事情。周六（0117）去安吉图书馆自学一下午，然后逛了附近的凤凰山森林公园，很自在。俺就要多放松一点，不能太[紧绷](../../posts/avoid-life-on-rails/)着。

# 第 04 周（0119-0125）

这周杭州下雪啦！气温也降低很多，上下班都是开驴驴。原以为去年开始 AI 的发展速度已经加速得够快了，没想到 2026 年加速度一点没有下降，大模型能力越来越从程序员下放到普通人。最近自己也在思考如何把自己的设备整合起来，有自己的数字员工替我干活，也尝试了 [tailscale](https://tailscale.com/) 或者内网穿透的工具将自己的设备都组合起来。

周末场子赶起来：杭州→安吉→桐乡→杭州→安吉→杭州，全程 360 多公里，小白酱辛苦啦！

工作上最近开始承接一些新工作，我自己没想好要从哪里下手，但是不要怕，勇敢去尝试！

# 第 05 周（0126-0201）

感觉时间真快，转眼已经是二月，马上就要过年了。本周的工作强度大，并且都是些难处理的活，出四季度主管奖励方案、年终奖方案、调研面向总经理汇报的主管调薪意愿、股权变更事项的跟进……好在周五（0130）都差不多提交方案，部分已经收尾。

另外，跟老板提了目前公司流程架构会导致未来的问题并给出初步方案，牵头去解决，拉上人力行政财务运营研发法务讨论，等着法务出方案意见ing。

周六（0131）和小王回安吉，她麻麻办年会，帮忙理顺了年会场控的 PPT，另外用开源的[抽奖程序](https://github.com/LOG1997/log-lottery)把抽奖给做了，致敬开源大佬，运气好还抽到了一支牙膏。

周日（0201）吃完午饭回家，给小白加满油，年底油价又要大涨咯！下午在家改 PPT。

# 第 06 周（0202-0208）

离春节越来越近，过年的氛围浓厚起来，同事之间已经在聊过年的安排。工作上仍然忙碌，好在已经习惯，另外再坚持一周就可以彻底放松下。

周六（0207）和小王回安吉，已经有春运的感觉，平常一小时不到的车程，硬是开了将近两小时。吃完午饭回桐乡，姐夫找人手把家周围建设了一番，连菜园子浇水都省事了。因为今年过年不回家，所以把给奶奶、外甥、外公外婆的红包都发掉咯！

周日（0208）和家人聊聊天，吃完午饭带了家里的菜到安吉，一份给陈兄，一份给小王粑粑麻麻。晚上在小王家吃年夜饭，还收到了她外婆的大红包。结束回杭州，来整理下被建国搞乱的房间，这次它把书都翻出来了。

# 第 07 周（0209-0215）

周二（0210）上班路上小毛驴的后轮开始漏气，停在路边扫小单车去公司，中午回去找维修店，但都关门回家过大年了哈哈！勉强骑回公司，美团上找了上门维修，不到两个小时就搞定。晚上骑上小毛驴去吃公司组织的年夜饭。

春节前大家都没有太多心思工作，公司提前两天放年假，我也抓紧完成手上紧急的工作。本周还体验了去银行大额转账、和法务拟好新的股权协议模版以及个别人员专用的模板。

周四（0213）上完节前最后一天班，晚上回桐乡。周五（0214）去外婆家逛一圈，再去医院看看姐姐和外甥女，八斤二两的娃娃肥嘟嘟的；下午赶回杭州给建国准备过节的口粮、水和猫砂，把家里的两口锅都用上了，安好监控便和小王一起出发去萧山机场直飞西班牙，今年小王爸爸妈妈和我们一起去西班牙和她姐姐过新年。

西班牙时间周六（0214）早上到达，小王姐姐和她同事来接我们到她家，关于在西班牙的所见所感，待日后单独写一篇记录咯！

# 第 08 周（0216-0222）

西班牙时间周六（0221）中午起飞回杭，北京时间周日（0222）早上抵达，赶紧回家看建国，屎盆子差不多都拉满，口粮还有剩余，收拾收拾，给建国上称发现它胖到快 12 斤了，完全一个肥猫。收拾完休息下回桐乡，年初六还能享受高速免费，路上车多些，尤其是许多新手上路，开车需要尤其小心。

今年的春节差不多就这样过去啦，还有一天修整修整准备上班咯！

# 第 09 周（0223-0301）

周一（0223）在家，有点感冒咳嗽，休整休整下午返杭，开启我的上班带饭大业，起因是过年没咋吃预制菜发现皮肤变好了。在盒马买菜送上门，为下定后续继续带饭的决心，怒开一年盒马会员。第一次带饭把控不好，饭多煮一半，菜做了五个，牛肉卤到晚上九点多，这一周吃得是丰盛。带饭之后还发现：中午午休时间变长咯，差不多有一小时，可以好好休息。

周二（0224）开工，换上财神爷皮肤给大家发开工红包，希望自己今年也事事顺利！周六（0228）调休上班，公司组织管理+部分人员去径山寺，在寺庙里边吃素面，喝了桂花燕麦拿铁，在山顶放空，晚上团建吃完饭才返程。晚上到家还给小主机的电源换猫扇，这下彻底解决噪音问题。

周日（0301）和小王去她外婆家吃午饭，又斗胆尝试新的理发店，效果不错。下午晚些就回杭啦，逛盒马，买好菜回家做饭。这次米饭正好，菜四个：番茄鸡蛋、包菜炒火腿、土豆丝、牛肉丁，另外加几块卤牛肉。

# 第 10 周（0302-0308）

月初给各部门提供数据，组织架构调整后又有审批流要微调，都是些琐事。在闲鱼上花一块钱买启信宝的体验账号看企业数据，发现数据还挺丰富的。

周六（0307）去安吉做健康论坛工作人员，会场选在环境优美的农庄里边，又正值淡季，在里边散散步也休闲舒适。

周六（0308）继续备菜做饭！上周吃下来发现米饭还是少一些，这次多加半碗米。菜五个：洋葱炒蛋、西蓝花炒虾仁、包菜香干、小炒鸡（炒成辣子鸡了）、爆炒牛肉丁。

# 第 11 周（0309-0315）

本周有外出去开会，有客户来接待，被交代了自己不喜欢但别人做不好还被压缩了工期的项目。周五（0313）下班回家备了下周五天的菜，把盒马会员日改成周四，周四可以预定周五配送，这样会员日八八折的优惠就物尽其用啦！

周六（0314）下午参加不久前被邀请加入的社群线下聚会活动，很有幸在加入不久之后就在杭州有聚会，下午天气好登了十一公里的小单车过去。一共七人，有技术有编辑有主播有联创，大家在小河直街散步，每人做了从高中开始的自我介绍，讲了讲 MBTI 和未来想做的事情。晚上一起吃了面后散场，很精彩的聚会。

周日（0315）早上介绍朋友和导师认识，聊的话题横跨五湖四海，饭后散步消食结束，朋友送我到家附近，开上小白去西站接从义乌考察回来的博哥和他媳妇。一起在西溪湿地散步喝咖啡，聊聊后续规划，晚上兴哥也来一起吃了饭，十点左右散场送各位朋友到酒店和家。真是充实的周末呀！

# 第 12 周（0316-0322）

周三（0318）去趟上海财大，返程极限赶高铁，下地铁离高铁出发还有 15 分钟，跑得我喘鼠，第二天都腿酸。周四（0319）西湖龙井头采，大晚上和行政主管两人被老板叫去翁家山提茶叶。周五（0320）和 ZY、YQ 一起整理 YQ 退休后暂存在教室的资料，居然整理到凌晨 00:40，也是见过凌晨的校园了，送 YQ 到家后赶紧回家洗洗睡觉。

周六（0321）小王去拔智齿吓哭了，俺回家前先去医院给她打打气，拔完后她在医院观察，俺先回家。在家看三楼老房间如何装修，用 ChatGPT 帮我先画了草图。周日（0322）回学校和十位小伙伴交流 AI，感谢 LP 和 XH 老师提供的场地和蛋糕，还请我们吃晚饭。第一次线下活动很开心很受鼓舞，算是一个好头，未来继续加油吧！

# 第 13 周（0323-0329）

日复一日的工作好像没啥好记录的嘞，周末倒是丰富得很！周六（0328）带小王和前同事见面，她请我们吃海鲜小火锅，如我预想一样，她们很聊得来；晚上和 XG 一起吃饭散步侃大山；回家用 Claude 做幻灯片上瘾搞到凌晨一点多。周日（0329）睡懒觉，下午和一位企业创始人聊聊天，他介绍未来想做的事情，称这是他的最后一次创业。

感谢 Copilot 大善人，用上了 Claude 模型，1M 的上下文确实打开新世界的大门，未来探索的路上，要有这么多强力的模型加持才行呀！

# 第 14 周（0330-0405）

这周和部门的助理以及之前带过的毕业生聊一聊，他们有异动的想法，这是我成为管理者以来第一次处理这类事项。当前我自身疲于工作事项，没有心思再去带新人，因此倾向于让他们留下来，即便是度过当前这个阶段也好。老板说长痛不如短痛，但我仍尝试再挽留一下，下周就要收答复见分晓。

应小王麻麻的邀请，周五（0403）做线上的 AI 分享，在线有六七十号人嘞，反响很不错，让我更加自信。

周六（0404）睡个懒觉起来回家，清明高速免费，路上车很多。考虑到后续可能会有在家办公的情况，此前麻麻提出装修下三楼的房间，我认为有必要，但也不急。这周休息时在淘宝物色了几款书桌，到时候买来装上就能丝滑办公。如果以后能阶段性在家办公，那也爽之。

# 第 15 周（0406-0412）

周一（0406）是最后一天清明假，吃完饭回杭，应老板需要，支持资料梳理事项。周二（0407）下班火速赶往萧山机场，坐上晚班飞机去北京参加卡兹克组织的 AI 未来大会，落地北京打车到酒店已是凌晨一点。在北京遇到了 WY 学妹，她负责她们公司在未来大会外部展台的布置工作，周三周四两天俺是又吃又拿的，未来大会也精彩纷呈，收获满满。周四（0408）晚飞杭州的飞机因为杭州的暴雨延误一小时，落地杭州到家已经凌晨两点。周五（0409）睡个小懒觉再去上班，邀请钉钉的服务商为公司业务部门提供产品介绍，另外收拾一些出差留下的细碎事项。

周六（0410）去西溪湿地和几位朋友聊天吃午饭。周日（0411）准备下周的饭菜，吃完午饭去参加公司组织的产品讨论，这次俺订了西湖边的茶馆；结束赶往城西银泰和小王还有 WY 一起干饭，这次俺做东。

# 第 16 周（0413-0419）

这周开通了 ChatGPT Pro，网上说 ChatGPT 降智，目前没感受到。用下来有一个体会：智能即服务。

老爸手腕手术住院，周四（0416）请年假回去探望。在爸妈的知情和支持下，这周我的职业生涯迈出改变的一步。和老板简要线上沟通后，他说下周一给我方案。

周六（0418）早上去安吉，顺便理发；下午和一位安吉的企业家朋友（线上 AI 分享的时候认识）聊天，一是组织管理上的问题探讨，二是他帮我分析现状、给我职业发展建议。周日（0419）吃好晚饭返杭。这两天渐渐阶段性认识：要更聚焦个人发展，减少精力外泄。

# 第 17 周（0420-0426）

周一（0420）中午老板和人力总请我吃大餐，老板给出后续合作的过渡方案，符合我的规划和公司需要，我当场答应，饭吃得很开心。

租的房子是两室一厅，其中一个卧室主要是放置衣物的。考虑到后续在家办公很频繁，着手把这个卧室改成书房。联系了房东，他说有空可以来把床搬走，我便先把床拆了腾出空间。这周买书桌、小地垫，把原先卧室的台式机和显示器都腾挪过来，顺便给台式机清灰，理线又折腾一遭，崭新的工作区初具雏形！

周五（0424）公司春游，去半山森林公园徒步吸氧，这天也是我两位同桌（部门助理和行政小伙伴）的 last day。看惯了公司人来来去去，即便是身边的伙伴，好像也没有太大的情绪波动。

# 第 18 周（0427-0503）

这周承接总经办所有事项，总归是忙碌。常规事项之外，对接外部股东讨论股权事项，还有个人交接的梳理。此外，学习当前 Agent 框架，也和研发部门了解当前内部使用的技术架构。

周二（0428）部门新人入职，带他了解公司和部门、讲解产品、干饭。本周公司新任 CMO 到位，周四（0430）给她培训公司今年的战略目标。

周三（0427）做服务器的小主机主板亮红灯，拆开细瞅一眼是 VGA 灯在亮，赤小资购入显卡欺骗器一枚，插上就搞定。周日（0503）又给小主机的固态硬盘装散热马甲，这台小机子也是折腾很多回了哈哈。

周四（0430）是和小王五周年，下班后去小河直街的意大利餐厅吃晚餐，带了从西班牙扛回来的白葡萄酒。时间真快，这次朋友圈的文案是：各自生猛，彼此照亮，五周年！

本周五一啦！周五（0501）睡个懒觉，下午把冬天的衣服、电热毯带回家，在家的时间也总是飞快，休息两天，周日（0503）返杭。维持和平常周末一样的作息，一是还有事情需要回来处理，二是未来两天假期体验下在家办公，为未来居家做模拟。如果自制力不好还可以想办法预防，设置下防护栏。

# 第 19 周（0504-0510）

五一终于实现今年的第一次出车🚴，和兴哥绕西溪湿地骑行一圈，晚饭吃川菜。五一最后两天体验居家干活，效果不错，强度也高，以至于开工第一天觉得上班舒服，没有在家那么高强度用脑。

本周继续承接部门所有事项，顺便用 GPT-5.5-Pro 帮其他部门搞定一些问题，有时候觉得很有趣：他们提供资料，我写提示词，借助顶级的大模型，就能解决他们的需求。另外，花时间琢磨智能体的实现，在企微接入了两个机器人，都部署在家里的小主机上。研究这些乐此不彼，接下来的努力方向是让它们能做更快更稳健地做更多事情。

周日（0510）母亲节，因为要去大健康论坛做工作人员，没法回家给麻麻亲手送上祝福啦，小王提前给麻麻买了礼物，俺今天发了小红包。晚上本想和小王吃一家老店，无奈排队人太多，尝试了附近的小龙虾，也是美味！

# 第 20 周（0511-0517）

本周家里的工位正式布置完毕，现在主力设备是：MacBook Pro + Apple Studio Display + ARZOPA 2.5K 16寸便携屏，挂上 BenQ ScreenBar Halo 2，坐在电脑前码字是享受。

周末天气好。周六（0516）在家学习，下午出发去学校吃饭、溜达、打坐、逛超市、在图书馆看书写博客，21:30 回家。周日（0517）组织公司小伙伴去塘栖摘枇杷，老板掏钱，又摘又买。同之前摘葡萄和杨梅，我载很多去放公司，这次因贪恋回复消息导致多停车一分钟需要支付六元停车费，拍烂大腿。

# 第 21 周（0518-0524）

部门新入职的助理，这两周看下来融入不顺，也没感受到他强烈的个人意愿。和老板沟通了一下，周五（0522）和他交流，让他看看外面喜欢的工作，当前的岗位确实不合适。

这周开始[看论文](../../posts/back-to-paper-reading/)，一开始用 deepseek-v4-flash 翻译，真到读的时候发现翻译得太生硬。于是切换到腾讯刚发布的翻译模型 [Hy-MT2-7B](https://huggingface.co/tencent/Hy-MT2-7B-GGUF)，用 4060Ti 部署，MacBook 内网调用，翻译质量好很多。有趣的是翻译了一个多小时的论文，整个房间都热乎了。

这周末哥哥结婚，他们倆筹划了很久，尤其是草坪婚礼的环节，是我参加过最有心意的一场，我和小王不约而同地认真做好氛围组角色。

<!-- 天亮和佳怡 -->

# 第 22 周（0525-0531）

又是忙碌的一周，工作交接进展缓慢，调整下思路，直接在我手上完结得了。之前外部股东购买公司股权的事项，对方已打款，接下来要处理内部的变更。财务复核好不容易交接掉了，复核盾给到财务大大，省不少时间。在高密度做事情的同时，闻到自由的味道。

周五（0529）大学好友来杭州，三年没见，我们一起请导师吃晚饭，叙叙旧，小王陪她玩了两天。周六（0530）带上朋友去长乐林场亲近大自然，散散步，晚上一起在吃学校附近的冒烤鸭。  <!-- 一卓 -->

最近 Codex 功能更新很多，趁着额度重置前，捣鼓好了对接钉钉 OA 审批流，可以定制内部看板。顺手试着写个[「飞机大战」](https://shitao5.github.io/plane-shooter-game/)的小游戏，是小时候喜欢玩的。

# 第 23 周（0601-0607）

这周部门两位新人到位啦，慢慢带起来！

周三（0603）开小白去上海财大出差，去的路上和老板财务总商量好，晚上吃饭我们悄悄把单买了。晚餐时财务总咔咔咔一顿点餐，没想到对方看出我们跃跃欲试，提前把单买了哈哈哈。结束时对方还让餐厅准备了很有心意的酸奶，大伙儿高兴，俺付了服务员小费。晚上回来的路上遇到几场小暴雨，安全第一，稳稳返杭，到家已是零点。

周六（0607）去杭口检查牙冠，拍了 CT，牙冠没问题，根尖炎症也完全消失了，另外发现两颗蛀牙，下周去补上，这次先洗了牙。想到上次洗牙还是 2018 年在天津呢。看完牙[回家干农活](../../posts/back-home-farm-work/)，晚上和麻麻去外婆家聊聊天。

周日（0608）早上六点半出发返杭，公司采购了外部的管理培训课，俺作为工作人员早点到公司布置培训会场，同时作为助教学习和观察。晚上还赶上了和朋友们聚餐，回家倒头就睡啦！

# 第 24 周（0608-0614）

周一（0609）管理培训结束，老板请大家去未来科技城高空餐厅吃大餐，俺也喝上七八两黄酒助助兴。

部门两位新人培养方向不一样：一位侧重日常工作，我慢慢把三年来安排行程、处理内部流程的经验分享给她；一位侧重技术，老板计划未来给内部做一些提效工作，俺得和他聊聊技术上的事儿。这周还再面试新人，团队继续壮大起来。

四月底和老板沟通确认过交接完手上工作后我不再固定工位办公，但手头事情实在是太多又太难交接，一眨眼到六月中旬了。周五（0612）和老板坐下来聊了聊，确定时间点为七月；另外和老板交流我对公司内部管理上的观察和想法，以及我的职业规划。老板说我已经在公司三年多了，是时候走出职业生涯重要的一步了，想好就认真去做，像朋友一样的聊天，我很感动和感激。

周六（0613）在家看书看论文，也首次尝试做土豆丝饼。周日（0614）和小王去杭口，她洗牙我补牙，又蛀了两颗牙真是册那。从杭口跳槽来我们公司的同事给了俺两支她用饭卡余额换来的含氟牙膏，好好刷牙！晚上和小王去大学时期就吃过好几次的日料店，时隔多年它还坚挺着，吃上美味小王很开心。吃完逛了下商场和盒马美美回家。







