---
title: '2024 年周总结'
author: 吴诗涛
date: '2024-01-01'
slug: 2024
---

<br>

::: fullwidth
```{r message=FALSE, warning=FALSE, out.width="100%", echo=FALSE}
# 根据2024年运动记录表作图
record = read.csv("sport.csv")
record$日期 = as.Date(record$日期, format = "%Y-%m-%d")

today = ifelse(Sys.Date() >= "2024-01-14", Sys.Date(), "2024-01-14") |> as.Date()

library(echarts4r)

record |>
  e_charts(日期) |>
  e_line(骑行, name = "骑行️🚴", y_index = 0) |>
  e_line(跑步, name = "跑步🏃", y_index = 0) |>
  e_bar(跳绳, name = "跳绳🪢", y_index = 1) |>
  e_x_axis(type = "category", axisLabel = list(formatter = htmlwidgets::JS("function(value, index) {
    var date = echarts.format.formatTime('MM-dd', new Date(value));
    var dayOfWeek = ['日', '一', '二', '三', '四', '五', '六'][new Date(value).getDay()];
    return date + '\\n周' + dayOfWeek;
  }"))) |>
  e_y_axis(index = 0, name = "公里数") |>
  e_y_axis(index = 1, name = "个数") |>
  e_datazoom(startValue = today - 12, endValue = today + 1, toolbox = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_mark_point("骑行️🚴", data = list(type = "max")) |>
  e_mark_point("跑步🏃", data = list(type = "max")) |>
  e_mark_point("跳绳🪢", data = list(type = "max")) |>
  e_title("运动情况", "每周日更新") |>
  e_toolbox_feature("restore") |>
  e_toolbox_feature("saveAsImage") |>
  e_grid(top = '17%') |>
  e_legend(top = "3%") |>
  e_color(c("#B80000", "#5F8670", "#FF9800"))
```
:::

# 第 01 周（0101-0107）

工作：

1.  开年第一周真是忙裂开！
2.  周四（0104）在同事的协助下给老板订了出差的[机票](../../posts/first-flight-ticket/)和酒店。
3.  周日（0107）[第一次](../../posts/overtime-request/)周末加班一下午。

生活：

1.  周五（0105）杭州补贴申请到账。
2.  周日（0107）小王和郭子买了菜，煮了大盘鸡拌面，好吃。

下周：

1.  [《详谈：赵鹏》](https://learn.shitao5.org/posts/20240106-xtzp/);
2.  [《荣格自传》](https://learn.shitao5.org/posts/20231228-rgzz/)；
3.  [学习 Web 开发](https://learn.shitao5.org/posts/20231217-web/)；
4.  [《行为设计学：让创意更有黏性》](https://book.douban.com/subject/30390604/)（Kindle）。

# 第 02 周（0108-0114）

工作：

1.  逐渐成为买机票熟练工，值机抢座熟手。
2.  周四（0111）催着刚毕业的同事赶快去申请毕业生补贴。
3.  在工作中思考如何提高开会的效率，目前想到一个法子，下周开始试用看看效果。

生活：

1.  周六（0113）上午回家，家里在装修，带去了劳动力和一点小资本。
2.  周日（0114）和姐姐剥晒干的丝瓜，丝瓜络拿来洗碗。

下周：

1.  [《详谈：赵鹏》](https://learn.shitao5.org/posts/20240106-xtzp/);
2.  [《荣格自传》](https://learn.shitao5.org/posts/20231228-rgzz/)；
3.  [学习 Web 开发](https://learn.shitao5.org/posts/20231217-web/)；
4.  [《行为设计学：让创意更有黏性》](https://book.douban.com/subject/30390604/)（Kindle）。

# 第 03 周（0115-0121）

工作：

1.  本周拍摄了年会上的一个视频，也提供了自己的麦克风和耳麦，事后是后悔的。
2.  周五（0119）晚公司年会，做了场控，不喜欢这样的氛围，早早溜了。

生活：

1.  周三（0117）完成人生第一个半马，用时 109 分钟。
2.  周日（0121）第一次跳绳达 7000 下。

下周：

1.  [*Mastering Shiny*](https://learn.shitao5.org/posts/20240119-mastering-shiny/)；
2.  [《平面设计中的网格系统》](https://learn.shitao5.org/posts/20240121-grid-systems/)；
3.  [《荣格自传》](https://learn.shitao5.org/posts/20231228-rgzz/)；
4.  [《行为设计学：让创意更有黏性》](https://book.douban.com/subject/30390604/)（Kindle）。

# 第 04 周（0122-0128）

工作：

1.  帮助同事处理数据两次：正则表达式提取手机号、260 万数据处理。
2.  写了对外的报告。
3.  大致明确未来两月的工作。

生活：

1.  周三（0124）是和小王在一起的 999 天，准备了鲜花和蛋糕作为惊喜，还用 GoPro 记录了惊喜瞬间。
2.  周六（0127）载着 GoPro 去学校骑车，剪了[视频](https://www.bilibili.com/video/BV18D4y1f7VX/)；
3.  周六（0127）晚和兴哥一起吃饭，开着驴驴去天街逛逛，聊聊天，顺便给侄女买了过年礼物。
4.  周日（0128）和小王逛小区外新开的水果店，第一次买甘蔗吃。
5.  周末在家吼两嗓，唱歌实习生。

下周：

1.  [*Mastering Shiny*](https://learn.shitao5.org/posts/20240119-mastering-shiny/)；
2.  [《平面设计中的网格系统》](https://learn.shitao5.org/posts/20240121-grid-systems/)；
3.  [《定投改变命运》](https://learn.shitao5.org/posts/20240123-dtgbmy/)；
4.  [《行为设计学：让创意更有黏性》](https://book.douban.com/subject/30390604/)（Kindle）。

# 第 05 周（0129-0204）

工作：

1.  周五（0202）之前在项目部时参与的一个项目成交了第一单，原来的部门请我喝奶茶（虽然我不喝），还是开心。
2.  周日（0204）晚参加管理层聚餐，第一次喝白的，喝了二两好像没啥事，还能回公司干个活。
3.  年终岁末，各种杂事越来越多，已经慢慢把 [Logseq](https://logseq.com/) 作为记录事项的主力工具。

生活：

1.  周五（0202）晚下班和小王一起去杭师大门口吃本地鸡窝，这家店陪伴了我和小王从认识到实习到工作。吃完回学校走了一圈，已放寒假，没见着几个人影。
2.  周六（0203）发现 RStudio 的 Visual 模式很好用，准备多使用这个模式。下载了 Zotero，可以写写东西。
3.  本周阴雨连绵，骑行上班次数骤减，改成小毛驴上班。

下周：

1.  [*Building reproducible analytical pipelines with R*](https://learn.shitao5.org/posts/20240203-raps-with-r/)；
2.  [《王川宝典》](https://learn.shitao5.org/posts/20240203-wcbd/)；
3.  [《行为设计学：让创意更有黏性》](https://book.douban.com/subject/30390604/)（Kindle）；
4.  写总结。

# 第 06 周（0205-0211）

工作：

1.  本周降温下雪，驴驴载俺上班。
2.  年前最后一周，大家的心都慢慢飞走了，唯有老板忙着收尾，并为来年做准备。老板回家前，送他到地下车库，他说要离开公司回家了，有点伤感。
3.  坚守到了最后一天，见证了春节临近公司的变化。

生活：

1.  周四（2.8）中午下班回家，买了好利来和汪保来，老兵码坐地铁，一路很顺畅。
2.  周五（2.9）除夕晚，照例睡得很早（十点前已经美美入睡），哪管外面鞭炮声天。
3.  周五（2.9）去买菜，周六（2.10）上海大伯家一行人来家里吃饭，摆了两桌。这次喝五粮液，发现自己好像真有喝白酒的天赋。大伯们问我近况，和他们简单说了说工作，然后和他们聊了很多。
4.  周日（2.11）全家总动员，把[年前装修](../../posts/manual-work)拆下来的木头门窗锯成柴火。

下周：

1.  [*Building reproducible analytical pipelines with R*](https://learn.shitao5.org/posts/20240203-raps-with-r/)；
2.  [《王川宝典》](https://learn.shitao5.org/posts/20240203-wcbd/)；
3.  [《财务自由之路》](https://book.douban.com/subject/30328453/)（Kindle）；
4.  写总结。

# 第 07 周（0212-0218）

工作：

1.  周日（0218）开工，上来就是高强度，顶住。

生活：

1.  春节假期，在家看书、学习。家里翻新之后可以学习的地方变多了，小手一动，把路由器放到窗口，这样可以覆盖家里更广的范围。
2.  周五（0216）周六（0217）去城里把一直闲置的房子墙给刷了两遍。我是一个粉刷匠，粉刷本领强\~
3.  春节期间阅读、思考的深度大于工作时，第一次发现这个问题，需要思考总结下原因。

下周：

1.  [《王川宝典》](https://learn.shitao5.org/posts/20240203-wcbd/)；
2.  R 包文档阅读：[fusen](https://thinkr-open.github.io/fusen/articles/How-to-use-fusen.html) 和 [targets](https://docs.ropensci.org/targets/articles/overview.html)；
3.  [《财务自由之路》](https://book.douban.com/subject/30328453/)（Kindle）；
4.  继续写总结。

# 第 08 周（0219-0225）

工作：

1.  周一（0219）徒步登山团建，早上踏着小单车上龙井。过灵溪隧道时非机动车道的「火车头」开得很慢导致整个隧道的电瓶车都在按喇叭，夹在中间看看前面和后面感觉还挺有趣的。
2.  本周降温降水，驴驴载着我上下班。

生活：

1.  周五（0223）回家啦！周六（0224）元宵节虽然不吃汤圆，但还是要团团圆圆。家里的装修还在进行时，下次回家估计就差不多了，小王说拥有了田景房。
2.  547 大喜临近，好多事项操办中。希望轮到我的时候，移风易俗些。

下周：

1.  [*Introduction to Bash Scripting*](https://learn.shitao5.org/posts/20240223-intro-bash/)；
2.  [*Trust in Data Science*](https://dl.acm.org/doi/10.1145/3274405)；
3.  [《财务自由之路》](https://book.douban.com/subject/30328453/)（Kindle）。

# 第 09 周（0226-0303）

工作：

1.  杭州的天气真是孬，工作日下雨很磨人。
2.  工作时间一长，就会慢慢见识到离谱但又情理之中的事情。

生活：

1.  周一（0226）出考研成绩，身边有些二战的朋友上岸，非常开心。
2.  周六（0302）和周日（0303）都放晴，出门骑车啦！周日去了[青山湖环湖骑](https://www.bilibili.com/video/BV1Vi421Z7U7/?share_source=copy_web&vd_source=5a9c9150ffb5584239291e4d5b8e2e5c)，是 2024 年以来最远骑行路线。周日还在家唱歌，慢慢发现唱歌也让我很快乐。

下周：

1.  [*Statistical Thinking for the 21st Century*](https://learn.shitao5.org/posts/20240302-statsthinking21/)；
2.  [*Trust in Data Science*](https://dl.acm.org/doi/10.1145/3274405)；
3.  [《权力的 48 条法则》](https://learn.shitao5.org/posts/20240228-48laws-power/)；
4.  [《财务自由之路》](https://book.douban.com/subject/30328453/)（Kindle）。

# 第 10 周（0304-0310）

工作：

1.  收集市场团队的部分业绩考核情况。
2.  接待外部营销 2 次，客户 1 次，分别作为甲方和乙方去感受商务谈判。
3.  安排公司内部聚餐 2 次，并在聚餐后通过聊天获得聚餐人员对餐厅和聚餐的反馈。
4.  周五（0308）作为后勤人员参加团建。

生活：

1.  周三（0306）在小区楼下的理发店获得了一个炸裂的发型。
2.  周六（0309）骑行回家，周日（0310）开着姐姐的车载着自行车返杭。
3.  周五（0308）连着周末，过了一个[三天小长假](../../posts/three-day-weekend)。

下周：

1.  [*Statistical Thinking for the 21st Century*](https://learn.shitao5.org/posts/20240302-statsthinking21/)；
2.  [*Trust in Data Science*](https://dl.acm.org/doi/10.1145/3274405)；
3.  [《权力的 48 条法则》](https://learn.shitao5.org/posts/20240228-48laws-power/)；
4.  [《谈美》](https://book.douban.com/subject/26838438/)（Kindle）。

# 第 11 周（0311-0317）

工作：

1.  周一（0311）晚准备管理会议的内容到零点，骑车回家的路上冷冷清清。
2.  周二（0312）接待外部营销 1 次。
3.  周四（0314）职能部门团建啦，主要吃，不喝酒。

生活：

1.  大四曾拿过其他学院设立的奖学金，周三（0313）该学院团学的同学联系我，告知俺本周需要提供个人事迹文字稿和类似于回访的内容。拿人手短，周日（0317）加班加点终于写完了。
2.  周六（0316）姐姐订婚，好事多磨，俺抽签来的[2018吉祥文化珠联璧合金银套币](https://www.chngc.net/common/news-detail?id=59521)终于送出去了哈哈。
3.  应 QY 召唤，周末做熟悉的助教工作，和新手小王一起，在萧山、杭州和桐乡来回跑。周六（0316）开车 104 公里，周日开车（0317）231.2 公里。

下周：

1.  [熟悉](../../posts/ecs1) 99 大洋一年买来的云服务器；
2.  [*Trust in Data Science*](https://dl.acm.org/doi/10.1145/3274405)。

# 第 12 周（0318-0324）

工作：

1.  周二（0319）挑了花篮送给公司配合默契的团队。
2.  周五（0322）接待外部领导 1 次。
3.  本周天气回暖，大家似乎有些躁动，工作上也有一些小摩擦。应人力的需求，以总经办的名义发了全员邮件。

生活：

1.  周六（0323）和小王一起爬了十里琅珰，咱俩都是第一次用登山杖爬山，确实轻松不少。西湖龙井开始采摘了，游客络绎不绝。
2.  周日（0324）洗了自行车链条，清理了刹车片。出门骑行溜达，在杭师大门口买了衢州烤饼赶紧带回家给小王吃，她惦记好久了。还是以前的味道，就是涨了一块钱。

下周：

1.  [*Trust in Data Science*](https://dl.acm.org/doi/10.1145/3274405)；
2.  [*Efficient Linux at the Command Line*](https://learn.shitao5.org/posts/20240324-efficient-linux/)；
3.  [《漫长的危机》](https://learn.shitao5.org/posts/20240321-mcdwj/)；
4.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）。

# 第 13 周（0325-0331）

工作：

1.  本周统计了钉钉后台的数据，如果后续需定期统计，可以尝试搭建 Shiny 应用。
2.  周日（0331）晚接待了北京来的品牌团队，在西溪湿地餐厅点菜、吃了晚饭。 <!-- 秐合餐厅 -->

生活：

1.  周五（0329）请年假一天，坐在学校图书馆学习半天，中午和 PL 老师一起吃了饭，聊到毕业后工作情况、未来的发展等等。
2.  周六（0330）早起搭 Shiny，一口气写到了六点，写了 Excel 批量合并以及拆分两个[功能](http://120.26.131.2:3838/ds/)。
3.  本周末都是在家做饭吃，好吃+省钱。

下周：

1.  [*Efficient Linux at the Command Line*](https://learn.shitao5.org/posts/20240324-efficient-linux/)；
2.  [《漫长的危机》](https://learn.shitao5.org/posts/20240321-mcdwj/)；
3.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）。

# 第 14 周（0401-0407）

工作：

1.  周二（0402）又整起了 SQL，用来检查 CRM 系统使用情况，从数据库去统计相比直接使用 CRM 去统计简直天差地别，或许这里可以用下「降维打击」这个词。
1.  本周清明假期，周四（0404）到周六（0407）休息，工作日很忙碌，每天都十点之后。

生活：

1.  周三（0403）下班就回家了，家里仍在紧锣密鼓地装修。周四（0404）抽干了家里的井除味；周五（0405）开垦了一半下水道，用于后续浇灌水泥场地后排水；周六（0406）在家处理工作上的事情，主要是数据可视化，还和高中同学一起吃了饭。
1.  周五（0405）写好了[数据分析工具箱](http://120.26.131.2:3838/ds/)的表连接和简介部分，ChatGPT 4 的写代码能力确实很棒。
1.  周日（0407）早上七点出门，老爸送我到高铁站，坐高铁+地铁+步行来上班。
1.  清明在家思考了很多，摸索了很多，产生了很多新的想法，或许后面会慢慢发芽。

下周：

1.  [*Efficient Linux at the Command Line*](https://learn.shitao5.org/posts/20240324-efficient-linux/)；
2.  [《漫长的危机》](https://learn.shitao5.org/posts/20240321-mcdwj/)；
3.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）；
4.  [*An Overview on Edge Computing Research*](https://ieeexplore.ieee.org/abstract/document/9083958)。

# 第 15 周（0408-0414）

工作：

1.  本周部门来新同事啦！
1.  准备和全程参与了五六周年员工私享会。
1.  随机分配了十多万的联系方式供商务电销，偶尔工作上写写代码挺好玩。
1.  预定四次餐厅。

生活：

1.  周五（0412）晚和姐姐哥哥小王一起回家，去高铁站载了博哥二人，去镇上吃了阿能面。
1.  周末姐姐结婚。

下周：

1.  [*Efficient Linux at the Command Line*](https://learn.shitao5.org/posts/20240324-efficient-linux/)；
1.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）；
1.  [*An Overview on Edge Computing Research*](https://ieeexplore.ieee.org/abstract/document/9083958)。

# 第 16 周（0415-0421）

工作：

1.  再次尝试在市场部周会中引入书面汇报，后期看效果。
1.  给新来的算法工程师讲解之前的产品实现思路和代码，好在当时有「先见之明」重构过代码，讲起来很流畅。

生活：

1.  周五周六（0419-0420）小表姐结婚。
1.  周日（0421）和 LT、PL 还有一位大二的同学[青山湖骑行](https://www.bilibili.com/video/BV1AE421j7vy/)。

<!-- 老彭、天亮 --> 

下周：

1.  [*Efficient Linux at the Command Line*](https://learn.shitao5.org/posts/20240324-efficient-linux/)；
1.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）；
1.  [*An Overview on Edge Computing Research*](https://ieeexplore.ieee.org/abstract/document/9083958)。

# 第 17 周（0422-0428）

工作：

1.  和老板一起过了遍他的事项，他肯定了我的工作，告诉我后续事项较多，让我继续加油。

生活：

<!-- 正一 --> 
1.  周二（0423）托在学校工作的 YZ 去门口捷安特店里帮高中同学订了自行车。周六（0427）早上和小王一起去车店，陪高中同学提车。试骑结束付完尾款，骑上十公里去她家附近的城西银泰蹭饭。她说回家倒头就睡，起来屁股疼。好嘛，多骑骑，练个铁腚。
1.  买了腾讯云的服务器，搞事情！
1.  注册了一个十年的域名，SSL 证书搞了好久，终于齐活儿了。

下周：

1.  [《世上为什么要有图书馆》](https://book.douban.com/subject/30157597/)（Kindle）；
1.  [*An Overview on Edge Computing Research*](https://ieeexplore.ieee.org/abstract/document/9083958)。

# 第 18 周（0429-0505）

1. 给[数据分析工具箱](http://120.26.131.2:3838/ds/#)补上 Kindle 笔记整理、电子书格式转化等功能。
1. 捣鼓了仿朋友圈的[博客](../../moments/)，真有意思。
1. 五一假期三次长距离骑行，共计约两百公里。
1. 回家把家里的井水再一次[抽干](../../posts/drain-a-well/)，这次老爸还买了生石灰撒进去，希望这次井水可以没味儿了。
1. 近两周冒出很多想法，五一做了减法，后续继续思考。

<!-- 减法链接博客 -->

# 第 19 周（0506-0512）

1. 这周有两位比较熟络的同事离职，愿她们前程似锦。
1. 工作上做了考勤、流程时效方面的分析，需要注意数据源的一致性。
1. [《动手学大模型应用开发》](https://datawhalechina.github.io/llm-universe/#/)还剩最后一章，使用讯飞的 API 在 GitHub Codespaces 中进行了实操。
1. 单休的周日（0512）在家卤了牛腱子，非常成功，把自己的手都卤入味了。
1. 写好了[人生阶段性总结](../2023year)。

# 第 20 周（0513-0519）

1. 这周老板请客，订购了很多楼下的瑞幸咖啡，包装袋全程使用时间不超过十分钟，感觉很浪费。于是俺收拾收拾包装袋，抽空给还回去了。
1. 周六（0518）上午网易推荐了《希望你啊》这首歌，里边一句「希望你啊，偶尔抽空能见一面，而不只是对着那相片，这是爸爸妈妈内心的心愿」很触动我，下午处理完一些事项便回家。晚饭是在外婆家吃的，和舅舅和了点白酒（第一次）。
1. 周日（0519）早起和老爸一起干活。上午爬上枇杷树采摘、修剪（实际是用锯子锯）。家里的简易抽水泵出了点故障，中午一起修理整好了。
1. 周日（0519）开姐姐的车车回杭州，有个直角弯圈子打小蹭到了，吸取教训。

# 第 21 周（0520-0526）

1. 周一（0520）开始熟悉新键盘（狼蛛 F75 新月轴，雷霆黑），同时开始学习使用 VIM，目前已经互换 Esc 和 Caps 键，总是不小心退出聊天界面，一点点适应！
1. 本周处理了几个数据需求，在读取时遇到很多奇奇怪怪的事情。一是用 `rvest::read_html()` 读取的 xls 文件；二是 ANSI 编码的 csv 文件，用 powershell 批处理转为 UTF8 后再读取的。另外，这周重新了解了下 [duckdb](https://duckdb.org/)，以后千万级别的数据可以存放在 duckdb 下，方便后续使用。
1. 本周开始把公众号捡起来，更新一些内容。周日（0526）因为《易经》和一位粉丝加上了微信。
1. 周日（0526）上午去[骑车](https://www.bilibili.com/video/BV1Pz421a7ua/)啦，恭喜小王 2024 年以来第一次骑上 40 公里。
1. 周日（0526）下午去看租房啦，已经交了定金。新房租金比当前高几百块，条件好了很多，在同一小区，下周末搬家！

# 第 22 周（0527-0602）

<!-- 黄正一 --> 
1. 忙忙碌碌工作的一周，除了自己的活儿，还帮别的小伙伴处理了数据、拍了推广视频、当了趣味运动会工作人员、订了餐厅……月底了，质检工作照常进行起来。
1. 周三（0529）晚大学室友喊上俺去骑车啦，带上朋友一起，刷了西湖，五十多公里。
1. 周四（0530）心血来潮用 R 写了抓取每天人民日报的新闻，并绘制词云图的功能，找个时间做成日报形式的。
1. 周末两天大搬家，真是大工程，多亏了露营小车和一个小板车（在我大学时期也经常派用场），来回搬了十多趟。相比一年前刚毕业那会儿，多了不少东西。
1. 周日（0602）把之前攒起来的塑料瓶卖给收废品的大爷，和他一顿「讨价还价」，从十块变成十二块，大爷和我们都笑了。用最近比较火的词，就叫「情绪价值」。
1. 周日（0602）晚十点半收拾差不多，点上小烧烤，叫上好朋友来家里搓一顿。

# 第 23 周（0603-0609）

1. 本周最重要的大事情：俺组装自己的[台式主机](../../posts/my-new-desktop)啦！配置是：I7-13700K、32G 内存、2T 固态、无显卡。自己看着 B 站教程视频安装滴！一次点亮，很酷吧！
1. 每月初的管理会议是吴师傅最忙活的一阵子之一，这周又忙完啦！
1. 被喊去接待外部团队一次。  <!-- 央视董老师 -->
1. 和老板一起部门聚餐啦，俺订包厢，吃了日料噢！  <!-- 虹料理 -->
1. 统计考勤数据；检查了部分制度的执行情况。
1. 本周小王出差在外，俺「放飞自我」，去解除了驴驴的限速，现在是快驴。和同事一起去配钥匙，吃惊于配锁师傅一分钟配 2 把收 20 大洋，无语于 2 把都打不开门。
1. 周日（0609）和奶奶、小范一起下地干活，家里有半亩地出租，上面的桑树被挖掘机挖起来后需要搬回家附近。要是奶奶自己搬估计得好几天，好在小范搞来了皮卡（给家里送搭鸡笼的围栏时开来的），来回载了五趟，一上午搞完了。

# 第 24 周（0610-0616）

1. 这周帮部门梳理合同扫描归档的工作流程，要有标准流程才能提高效率。
1. 协助处理外部数据 1 次。
1. 周五（0614）下班去学校理发，然后和小王一起吃俺们以前经常光顾的「本地鸡窝」。
1. 周六（0615）发疯，早上四点多起来做早饭，五点多出门骑行，[190公里](https://www.bilibili.com/video/BV11M4m1m7e7)，腿上一点小晒伤，脸黑一圈，现在小王叫我「黑皮」（不开熏）。
1. 周日（0616）在家剪视频，i7-13700K 自带的核显也很强，导出嘎嘎快。
1. 周日晚（0616）和大二跨专业去公管上《组织行为学》认识的同学吃顿饭，喝了一斤黄酒。他六月底离职，工作一年让他发现自己喜欢的事情，准备回甘肃备考学校一位很关心学生的老师的研究生。以他的积淀妥妥的，俺就安心等好消息，等他回来请俺吃饭。

# 第 25 周（0627-0623）

1. 本周运动暂缓，做休整。开小毛驴上班真是惬意。
1. 本周开启新的工作事项，预计是未来一年的长期事项。
1. 周五（0621）兴哥请我和小王两人吃饭，祝贺他即将转正，也喝了一斤黄酒。
1. 周六（0622）在家捣鼓了[文本内容安全识别](https://github.com/Shitao5/tms-shiny)，主要是调用腾讯云服务检测社交媒体上的敏感词。做这个原因有二：
     1. 导师发的朋友圈经常被屏蔽，这个应用可以帮助识别敏感词，方便调整内容。正如和叶寻[谈到的](https://github.com/Shitao5/shitao-blog/discussions/42#discussioncomment-9769645)，我认为躲避平台违禁词是很卑微的行为，用户始终是高高在上的才对。
     1. 俺自己试一试用 Python 写项目。
1. 周日（0623）在家卤牛腩，非常成功嘿嘿！

# 第 26 周（0624-0630）

1. 本周预约餐厅 3 次，拍摄推广视频 3 条，更新了制度，发布了通报，处理了上千个 PDF 文件（使用项目部开发的工具）。  <!-- 合同 -->
1. 周五（0628）去上海出差，这是我工作后第一次去外地出差，参加了推介会和晚宴，喝了瓶 1L 装的特产啤酒，感觉味道很不错。晚上因为出租车师傅不认识虹桥火车站的路而高铁，候补无票，好在混上高铁补票回了杭州。
1. 周六（0629）和小王爸爸妈妈一起去西溪湿地吃饭啦！和小王在一起 1100+ 天，这是第一次正式和叔叔阿姨见面吃饭。
1. 下了一个多星期的雨似乎没有停的意思，周日（0630）在家闷得慌，下载了童年游戏穿越火线，登录后显示开始玩的时间是 2010 年 7 月 2 日。玩了几把，头晕目眩，看来过了玩游戏的年龄。晚饭后趁雨停的工夫，和小王以及朋友一起去天街逛了逛。

# 第 27 周（0701-0707）

1. 周五（0705）晚和小王下馆子吃日料。
1. 周六（0706）早六点半出门，骑小蓝车去西溪湿地北，坐 19 号线地铁到火车东站赶早班高铁回家，上午九点到家，给了麻麻一个惊喜。这个世界醒得早，大清早的地铁和高铁客流量也非常大。
1. 本周高温，迎来「大火收汁」，家里的黄瓜藤都被晒蔫吧了。周六（0706）晚打井水给奶奶的菜园子浇水。在空调里躲了两天，琢磨装好 Ubuntu 24.04 LTS 的笔记本，[装了微信](https://ubuntuhandbook.org/index.php/2021/02/install-deepin-wechat-qq-ubuntu-20-04/)，凑活着用。另外，根据《黑客与画家》的安利，开始玩一玩 Lisp。
1. 周日（0707）去外婆家吃晚饭，是舅舅煮的酸菜鱼哦！晚上蹭哥哥刚买的特斯拉返杭，路上聊得太嗨皮走错两个路口。

# 第 28 周（0708-0714）

1. 周二（0709）晚做舅舅啦！下班不久老妈发来消息，俺赶紧打车去省妇保看姐姐。
1. 周四（0711）老爸告知家里的冰箱坏了，京东上买了新的多门冰箱。奶奶总说冰箱太小不够放，新冰箱容积是旧冰箱的两倍，应该可以顶一阵。旧冰箱以旧换新，抵 70 大洋。
1. 周四（0711）整理了关于行程安排的经验分享。
1. 周五（0712）周六（0713）两天参加公司培训。
1. 周日（0714）看完[《找事：给年青一代的就业解惑书》](https://book.douban.com/subject/36491565/)。

# 第 29 周（0715-0721）

1. 周二（0716）公司六周年庆，和去年年会一样，俺去做场控啦！Power Point 可以扛住 4.1G 的幻灯片，还挺给力。晚宴去会场十来桌打一圈，消耗四五瓶啤酒。
1. 协助业务部门寻找外部供应商 3 家，初步了解一个细分的咨询赛道。
1. 完成公司培训的课后作业，作为组长的俺压力山大，好在组员们都灰常给力！
1. 完成老板临时安排的质检工作。下周开展主线的质检工作。
1. 俺又忘记自己的[生日](../../posts/25y)啦，好在家人们都记得。
1. 周末在家[熬](../../posts/oil)猪油、葱油，热得俺满头大汗，好在非常成功。
1. 同事离职后涨薪找到新工作，周五（0719）晚上叫上俺和其他两位小伙伴聚餐，俺顺带捎上了小王，这是去年公司团建后小王和他们第二次见面。<!--其实俺们还一起去试驾了特斯拉 modle3 和 modely，因为俺买车时想给爸妈一个惊喜，这里先按下不表。 -->

# 第 30 周（0722-0728）

1. 本周拍摄推广视频 3 条，参加公司内部培训，安排了一中学夏令营来访参观的接待，组织内部交流会 2 场，发布制度 1 条，预订包间和茶室共 3 次。
1. 周二（0723）迎接家庭第三位成员：[王建国](../../posts/my-cat)，是小王妹妹捡到的流浪猫，品种是三花。
1. 周六（0727）尝试本地搭建了大模型和知识库，后续看看有什么稀奇古怪的用法。
1. 周六（0727）晚上邀请朋友来家里吃烧烤，喝啤酒，聊聊天。
1. 周日（0728）做了用 Quarto 渲染美化 Logseq 笔记的 Shiny [应用](https://github.com/Shitao5/Logseq-markdown-output)，可以解决笔记分享不美观的问题。 

# 第 31 周（0729-0804）

1. 本周工作 3 天，休年假 2 天。三天工作日，协助部门同事处理大量的纸质文件，这是简单重复工作，把动作分解，流水线处理，计划一星期的工作在周三（0731）便收尾了。
1. 周三（0731）早餐嘎崩脆的酱香饼把牙崩掉一小块。周四（0801）上午去省口拍牙片，由于治疗比较麻烦，和小王讨论后决定去杭口治疗。周日（0804）下午拍牙 CT，不查不知道，一查也没吓一跳，有几颗牙都在等待治疗的路上，一颗先开始根管，慢慢来吧。
1. 周四（0801）下午回家，第一次抱大外甥。
1. 周五（0802）在家休息，体验下逝去两年的暑假。晚上约战友聊聊天，绕着凤凰湖走了两圈，又去吃烧烤，回家已是第二天。
1. 周六（0803）上午载着麻麻去市医院做检查，后来放心不下，挂了下午浙二的号，载着麻麻来杭州检查。吐槽浙二的叫号系统，加粗加大写着「迟到将重新排序」，结果是前面的号不管如何都是前面。医生开出抽血单后检验科已经下班，问了急诊抽血，他们说有些项目急诊没法验。好吧，周日早上再来一趟。

# 第 32 周（0805-0811）

1. 本周[受了些小伤](../../posts/tttyg)，需注意恢复。
1. 周六（0810）参加公司组织的外部培训，课程是《目标管理》。最大的收获是关于对沟通的划分：打招呼 -> 谈事实 -> 谈想法 -> 谈感受 -> 敞开心扉。
1. 周日（0811）早起去浙二给麻麻预约好了下周六的检查，医生说差不多可以确诊，还需要最后的确定。在浙里办吐槽了浙二的效率太低下，预约 9:30-10:00 的号，将近 11:10 才看上。

# 第 33 周（0812-0818）

1. 忙碌的一周，催各部门赶进度、「交作业」。
1. 关于上周日（0811）在浙里办吐槽了浙二，本周收到了浙二的两次回复：一是门诊的一个负责人询问了具体的情况，说后续会有改进，表示感谢反馈；二是浙二门诊办公室来确认了是否有相关人员联系我。流程上看内部有质检，期待后续有所改进。
1. 周六（0817）早六点多载上麻麻来浙二检查，半路扎了钉子，小心翼翼开到之后补了胎。
1. 周日（0818）给根管的牙齿换药，下次是三个月后。另外另一颗牙也开始根管治疗，俺可怜的牙牙。医生说我特别能忍痛，可不是嘛，忍得俺满头大汗。
1. 周日（0818）晚和小王一起去吃虹料理（海鲜自助）啦！这位小王小朋友居然小过敏了哈哈！
1. 周日（0818）晚看完[《中年之路：人格的第二次成型》](https://book.douban.com/subject/36139391/)了，这本书对我启发很大，几乎每一章节都是大段的摘录。把它放到我的二刷清单里边。

# 第 34 周（0819-0825）

1. 这周请了一天半年假，陪麻麻在浙二住院，做全麻气管镜检查。这是俺第一次给家人签手术知情同意书。周五（0823）下午出院，虽然气管镜检查结果正常，但根据前期的检查，还是决定先吃药治疗，后续再看看效果。
1. 周六（0824）早上继续俺的根管治疗，历年医保账户已经刷爆了，只能掏出俺的小钱钱。后面两颗牙齿打桩 + 牙冠，俺的小荷包危！
1. 周六（0824）一位朋友回杭州考 CPA 职业能力综合测试，晚上三个人一起吃了牛肉火锅，在西湖边散步聊天到凌晨。 <!-- 沙沙、兴哥 -->
1. 周日（0825）晚上骑车去溜达咯，好久没有骑车了，用上俺新入的 Insta360 GO 3S 拍一拍骑行第一人称视频。

# 第 35 周（0826-0901）

1. 本周忙忙碌碌。一是 995 开始；二是开通了意见直达总经理的渠道，需要俺协助处理；三是 CRM 质检后涉及处罚，商务反应很激烈，俺再全部核查一遍，再同步人力、财务进行处罚；四是协调研发和市场，对 CRM 系统进行改进。
1. 周五（0830）姐姐来杭州上牌，载着下班的俺回家咯！
1. 周六（0831）一大早起来收拾[我的小车](../../posts/my-car)，趁太阳公公还没发力把车里卫生搞了一遍，脚垫洗了洗。晚上太阳公公下山，装了行车记录仪，把姐姐的 ETC 拆下来，用[井水](../../posts/drain-a-well)洗了车。老爸说跟新车一样！
1. 周六（0831）晚载大表姐去看公路车，她也打算入坑。暂时未买，准备海鲜市场（闲鱼）瞅一瞅。
1. 周日（0901）早上载妈妈去医院检查肝功能，希望伏立康挫赶快把曲霉菌杀杀杀，然后可以停药。

# 第 36 周（0902-0908）

1. 本周检查了另一产品线的 CRM 使用情况并同步人力出具处罚意见。周四（0812）被老板喊去救火，熬个小夜，周五（0813）凌晨 1:18 搞定。
1. 周六（0907）早上去杭口继续根管，下周日（0915）准备打桩做牙冠。回来带[建国](../../posts/my-cat)去打疫苗，俺一个人花了不少功夫才把它装进包里，回来都和俺不亲了。午饭吃好给[小白](../../posts/my-car)装上 ETC，载上 <a class="link" href="../../posts/bikes/#第三辆-大学的自行车">I my bike</a>（它即将跟随姐夫去建德，协助姐夫完成减肥大业），去浙二给麻麻配药、预约 CT 和血检。
1. 周日（0908）回杭，[体验](../../posts/sfcczty)了一把顺风车车主，首单平台奖励 50 大洋，算上和乘客协商的高速费，到账 112.8 元，正好给小白喝上 95。晚上兴哥送来了他在绍兴采的好几种葡萄，然后我们一起去干饭（先启半步颠），吃完边走边聊，回家坐在阳台上吹风吃葡萄继续聊到十一点半，好久没有这么聊一聊啦！

# 第 37 周（0909-0915）

1. 本周赶上中秋节，大家节奏都慢下来，好多同事提前请了假，回家和家人团圆。周六（0914）调休上班老板提前一小时让大家下班了。
1. 周日（0916）下午给俺的左下 36 牙打桩做牙冠，这次工程量大，花了一个多小时。全瓷牙大大滴贵，护士说门诊费用达三万可以有优惠，俺开玩笑说所有牙都给你们治都凑不齐三万呐！医生笑了，说给个 95 折，这也够小白喝一箱 95 呢。这次取完模型，就等牙冠做好喊我去带了。口腔医院就在学校门口，做完顺路去学校理了个发。
1. 中秋赶上台风（贝碧嘉），家里蹲。

# 第 38 周（0916-0922）

1. 由于调休，这周仅工作三天，做三休四感觉很不错。
1. 周五（0920）晚上帮姐姐提她闲鱼淘的二手婴儿车后回家。晚上十点多高架很畅通，以后会多晚上回家。
1. 周六（0921）是赶场子的一天，早上六点从桐乡出发带麻麻去浙二抽血、拍 CT。结束后走高速十点不到回家，看爸妈做饭、逗侄子开心，十一点多吃好午饭返杭。下午 14:16 从杭州西站高铁出发去宜兴，小王的一位大朋友孩子百日宴，晚上宴请熟人小朋友，俺和他们一家初次见面却很投缘，两人喝了将近两斤白酒，是我喝得最多的一次。这下可苦了小王，大晚上搀扶着俺去做高铁、打车回家。
1. 周日（0922）早晨四点多醒来仍昏昏沉沉，泡一袋电解质粉补水，坐在沙发上发呆。后来想到买的剑麻绳到了，缠了桌腿给建国玩，没想到这个圆锥曲线形的桌腿特难缠，竟花了将近两个小时才完工。
1. 周日（0922）傍晚找了车少的路，带小王练车，愿她尽快成为老司机。

# 第 39 周（0923-0929）

1. 好一个调休竟让俺忘记更新周报，周一（0923）发现忘记更新，索性再晚点更新了。
1. 本周帮老板填了写信息表，用于一些事项。
1. 周日（0929）晚终于给俺的 36 牙带好牙冠了，看牙是花钱买服务，看完吃饭嘎嘎香。

# 第 40 周（0930-1006）

1. 周一（0930）是国庆节前最后一个工作日，老板发福利，提前半天放假。下午和小王回学校看看老师。
1. 周二（1001）国庆第一天，自己动手给小白加玻璃水，更换雨刮器、空气滤芯、空调滤芯。换空气滤芯的时候掰断了一颗螺丝柱，不影响使用。换空调滤芯的时候又掰断了一个滤芯卡扣，同样不影响使用；另外还把手套箱的阻尼器搞断了，导致手套箱一打开就 Duang 地一下下来，同时手套箱的照明灯没法亮起。淘宝十五大洋买个原装，周五（1004）自己加防冻液的时候，换掉就搞定了。
1. 周三（1002）和小王回家，吃完晚饭和麻麻一起去外婆家溜达。再晚点和海涛约了烧烤夜宵，小王觉得好吃又便宜，有她喜欢的黄金糕，以后还会去。吃完去南日公园散步消食，儿童乐园里有滑滑梯、攀岩小斜坡，我们玩得不亦乐乎。周四（1003）午饭后，前往小王心心念念的青山湖水上森林，尽情出片。
1. 周六（1005）和导师、兴哥一起环千岛湖骑行，早晨 6:30 开车从杭州出发，两个小时左右抵达。换好衣服开始骑行，欣赏一路风景，边骑边聊天。中午在汾口镇吃碗面继续出发，下午不一会儿就下雨，躲了一阵子的雨看没有停下的迹象，一狠心雨骑六十多公里，晚上六点半终于骑回终点。导师请客去本地鱼头馆吃鱼，一鱼两吃，鱼头汤浓郁鲜美，吃饱喝足九点，出发回家，将近十二点到家。
1. 周日（1006）在家扫地拖地洗衣服洗鞋洗自行车做饭剪视频喂猫写周报。

# 第 41 周（1007-1013）

1. 周四（1010）老板请五十多位同事喝星巴克，惊奇地发现这家星巴克做完我们的单之后居然关门休息了。
1. 本周单休，唯一休息的周日（1013），起床看两个小时书后，带小白去换机油。中午和同事朋友一家去老余杭吃牛肉，分量足、味道好、价格便宜，随手推荐给了导师。吃完去附近的南湖公园溜达溜达，送他们去 4s 店取他们维修好的车，俺和小王则一拐弯溜进西溪印象城，逛了逛优衣库和 ZARA，给俺这个没衣服的人添加些新「皮肤」。

# 第 42 周（1014-1020）

1. 本周统计了 CRM 所有正式客户的回访情况，老板开了市场主管会议，对不合格的进行了警告，但允许补充，下周俺得再检查一遍。
1. 周二（1015）给小王拿主意，下单 MacBook Air M3 16+512G，趁着政府补贴（2000）和京东满减（1400），8599拿下。她用了五年多 8+128G 的 MacBook Air 终于可以退役了。
1. 周四（1017）下单微星魔龙 4060 Ti 16G，京东居然做到了当日达。碰上公司周五（1018）举办财税大会，周四晚在西溪宾馆布置会场到晚上十一点半。回到家迫不及待给俺的[电脑](../../posts/my-new-desktop/)插上，一次成功，装好驱动和 CUDA，终于可以用 GPU 版的 PyTorch 了。
1. 周五（1018）晚十点左右出发回家，高架上不堵，听着音乐吹着风，很舒适。
1. 周六（1019）带麻麻坐高铁、地铁去浙二检查。在东站时，麻麻和我说上一次坐高铁来杭州是十多年前，带我来检查身体。这次一是来检查，二是带麻麻体验新事物，为她下周自己来浙二看医生做演练。今天（1020）剪了简单的教程视频发给麻麻。
1. 周六（1019）在家洗小白，淘宝一百多块的洗车工具全套（电动泡沫喷壶、洗车水蜡、洗车拖把等）挺好使，洗得干干净净。

# 第 43 周（1021-1027）

1. 这周恢复骑行上班。周末阴雨天，想去爬山而没有机会，宅在家里学 [Transformers](https://huggingface.co/docs/transformers/zh/quicktour)。周日晚（1027）开上小白回家一趟，把夏天用的风扇载回家，顺便给粑粑麻麻买点山姆零食。
1. 这周复核正式客户回访情况，涉及处罚，反应很激烈，再一次给机会，下周一（1028）中午截止。在检查过程中发现了一个比较严重的问题，暂时先记录不做处理。
1. 本周把 Logseq 笔记软件中摘录的句子做成了阅读卡片，目前共有 1028 张，放在服务器[云盘](http://49.234.56.82:5244/drive/Card)上，自己随时可翻阅，也方便分享。

# 第 44 周（1028-1103）

1. 周四（1031）被拉去拍推广视频，结果周五（1101）说没录进去声音，又重拍了一遍。晚上用 [black-forest-labs/FLUX.1-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev) 画出了第一张图，继续摸索。
1. 周五（1031）收到导师的需求，用 R 帮助他处理了一些 Word 文档。
1. 周六（1102）和小王一起回家喝喜酒，当天来回。
1. 周五（1101）晚小王骑驴驴去健身，回来半路驴驴断电了。周日（1103）推去车店检查，说是锂电池坏了，两个选择：换电池 650，以旧换新换新车再补 1900。悄咪咪淘宝一查，锂电池大约四百，算上满减 374 买了一块，等到了之后试试看；老板推荐的那款车淘宝 1799。
1. 周日（1103）晚和小王再去老余杭吃牛肉，结果人超级多、排队超级长！于是我们在旁边挑了一家淮南牛肉汤吃，好不正宗，巨咸！好在小王说吃什么不重要，重要的是和谁吃。

# 第 45 周（1104-1110）

1. 本周公布了 CRM 正式客户回访的结果，对过程中发现的弄虚作假行为进行了全公司通报。
1. 协助项目部处理了 350w 左右的数据。
1. 新买的电瓶仍然没能让驴驴跑起来，经历了略微曲折的退货（还得是顺丰）。周日晚（1110）推到小区门口的电瓶车电，等老板下周一（1111）开门了修修看。
1. 周末[去小王家](../../posts/qxwjgf)咯！

# 第 46 周（1111-1117）

1. 周一（1111）早上驴驴[修好](../../posts/llwxj/)啦！骑驴上班一周，失而复得的感觉真好。
1. 帮助行政部门把门禁系统给捣鼓明白了，把几台设备的指纹进行了同步。
1. 帮助忙不过来的老板给他的直属一二级主管进行公司的活动打分，老板说打得很好。
1. 老板不在，在公司楼下新开的东大方接待股东吃饭，聊得我嗓子冒烟儿，他对我服役的经历、退役、不考公的选择很感兴趣，说我受浙江营商氛围的熏陶，有个性和想法，欢迎我加盟公司。
1. 前期质检工作获得了认可，老板让我去申请奖励，已邮件申请。
1. 周末在和小王一起去宁波学习，结实了一些新朋友，网友面基。周日（1117）下午回来后去看我的 47 牙，拍了 CT，炎症吸收效果比较不错，医生说药再敷三个月。晚上和小王、小王麻麻一起交流学习成果。
1. 周日（1117）和同事一起预订了周一（1118）晚要用的轰趴馆，用事实上并不存在的「三寸不烂之舌」还价 300 元。

# 第 47 周（1118-1124）

1. 奖励到账啦！分配了一部分给协助质检工作的小伙伴，打点下关系。
1. 梳理了市场部过程管理指标，发现商务小伙伴工作也挺辛苦的。
1. 参与了战略研讨会，瞧见公司战略的摇篮。
1. 老板出差，第一次自己组织一级主管开会，讨论一个制度的初稿。
1. 受老板委托，整理职能及制度体系，工作量挺大，但是对了解公司很有帮助，一点点去啃。
1. 周三（1121）下班回家一趟，正好同事买山姆，买了瑞士卷带回家。
1. 周末去小王家，协助小王开展家庭健康管理员培训工作，认识了小王麻麻的一些同事。周日（1124）晚小王爸爸下厨，做了一桌丰盛的菜，吃完陪小王买了些衣服，便回杭州了。






























