---
title: '2025 年周总结'
author: 吴诗涛
date: '2025-01-05'
slug: 2025
---

<br>

::: fullwidth
```{r message=FALSE, warning=FALSE, out.width="100%", echo=FALSE}
# 根据2024年运动记录表作图
record = read.csv("sport.csv")
record$日期 = as.Date(record$日期, format = "%Y-%m-%d")

today = ifelse(Sys.Date() >= "2025-01-14", Sys.Date(), "2025-01-14") |> as.Date()

library(echarts4r)

record |>
  e_charts(日期) |>
  e_line(骑行, name = "骑行️🚴", y_index = 0) |>
  e_line(跑步, name = "跑步🏃", y_index = 0) |>
  e_bar(跳绳, name = "跳绳🪢", y_index = 1) |>
  e_x_axis(type = "category", axisLabel = list(formatter = htmlwidgets::JS("function(value, index) {
    var date = echarts.format.formatTime('MM-dd', new Date(value));
    var dayOfWeek = ['日', '一', '二', '三', '四', '五', '六'][new Date(value).getDay()];
    return date + '\\n周' + dayOfWeek;
  }"))) |>
  e_y_axis(index = 0, name = "公里数") |>
  e_y_axis(index = 1, name = "个数") |>
  e_datazoom(startValue = today - 12, endValue = today + 1, toolbox = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_mark_point("骑行️🚴", data = list(type = "max")) |>
  e_mark_point("跑步🏃", data = list(type = "max")) |>
  e_mark_point("跳绳🪢", data = list(type = "max")) |>
  e_title("运动情况", "每周日更新") |>
  e_toolbox_feature("restore") |>
  e_toolbox_feature("saveAsImage") |>
  e_grid(top = '17%') |>
  e_legend(top = "3%") |>
  e_color(c("#B80000", "#5F8670", "#FF9800"))
```
:::

# 第 01 周（1230-0105）

1. 2025 年啦！本周开始安排春节前后老客户回访和部分员工的访谈，老板春节前后行程满满。
1. 周末小王回安吉组织和参加健康管理员培训，俺做司机。和前几次不一样的是这次来回都顺风车接了单，小王说爱上了接单的感觉，她坐副驾凭啥说这个啊哈哈？！
1. 周末被[《天幕红尘》](https://book.douban.com/subject/24748615/)的剧情深深吸引，读了将近一半，风格和[《遥远的救世主》](../../posts/yaoyuandejiushizhu/)很像。记得后者是大学时连续两个晚上读到凌晨三四点，酣畅淋漓地读完的。虽然现在工作不能这么疯狂了，但一个星期断断续续拿下还是没问题的。

# 第 02 周（0106-0112）

1. 老板北京出差半天，还要赶去嘉兴参加晚宴。协调好北京的两个行程，安排萧山机场的接机专车，一切顺利。
1. 周四（0109）人力资源部公示了 2024 年度优秀员工，有幸上榜。
1. 周五（0110）公司在西溪湿地举办年会，做了一天工作人员，晚宴上顺利给老板替酒。这次年会少了很多敬酒环节，太爽了！
1. 周六（0111）带[建国](../../posts/my-cat)出去社会化训练，目前可以躲在背包里观察外面的世界，目标是不怕人，因为年底要带建国回小王家里住。
1. 周六（0111）晚和小王一起回家，路上接顺风车一单，然后去南日吃烧烤，那里有小王心心念念的黄金糕。
1. 周日（0112）姐夫带了七八个全能型工人来改造下家里和家边上的设施，预计工期两天。俺也下地忙活一阵子，和奶奶一起把未成熟的榨菜翻起来，好移植到别处去。

# 第 03 周（0113-0119）

1. 本周继续组织一些与公司 2025 年战略相关的会议。
1. 周四（0116）晚上送小王回安吉，她姐姐从西班牙休假回来，也是俺第一次见到她姐姐。我们仨和小王粑粑麻麻一起吃了烧烤，我在小王家住宿一晚，周五（0117）早上吃好早饭回杭州上班。
1. 周五（0117）晚上约上朋友在天街吃饭。
1. 周六（0118）一个人在家，放飞自我。看了 [openxlsx2](https://janmarvin.github.io/openxlsx2/index.html) 的文档，拓展用 R 和 Excel 打交道的能力，其中 [wb_dims()](https://janmarvin.github.io/openxlsx2/reference/wb_dims.html) 函数很有趣，要找时间看下源码。还一展歌喉，对自己的五音不全程度有了更深刻的认识。晚上嘴馋，点了几片三文鱼，省下一小块给建国尝，这家伙居然不吃。
1. 周日（0119）早起煮馄饨，而后去杭口检查俺的 47 牙，CT 显示根尖炎症好了很多，重新封牙，三个月后再复查。看牙结束去小王家，顺路接上顺风车乘客，送他们去爬山，跑山之后小白都好开了。晚上小王麻麻组织团队年会，场控的任务交给了俺，于是抓紧准备 PPT 和背景音，和主持人对了流程，晚上一切都顺利。年会非常热闹，大家喝酒唱歌聊天，将近九点才结束。结束已晚，俺便又在小王家住宿。

# 第 04 周（0120-0126）

1. 本周 2025 年各部门战略敲定，在年前最后一个工作日（0124）下班前发布了全员邮件。
1. 本周销售 VP 到岗，由于行政部人手不足，外加 VP 的助理还在招聘中，老板吩咐我多关照下 VP，帮助布置了办公室、安排了住宿酒店，也看了看周边的租房。
1. 周四（0123）晚送小王和建国回安吉，周五（0124）早上回杭州上班。建国适应了两天，已可以在小王家巡逻，并和它的两个哥哥（芋头和面条）一起玩耍。
1. 周五（0124）晚留下来看着阿姨收拾公司卫生，检查完门窗、水电，和老板打声招呼，俺 2024 年最后一个工作任务圆满完成。
1. 周六（0125）上午睡个小懒觉，起床收拾下，把驴驴充满电在地下车库停好，开上小白载满一车年货，回家过年！到家老爸正好煮好羊肉，美美吃上。
1. 周日（0126）载麻麻去烫头发，期间去外婆家吃饭，给小外甥买了帽子。

# 第 05 周（0127-0202）

1. 春节假期，不再以星期算日子，取而代之的是农历。
1. 除夕（0128）给小白换了一对前轮，马牌 UC7，新年换新鞋。
1. 初一（0129）早上带上给叔叔阿姨的新年礼物，去安吉接小王来家里吃午饭和晚饭。晚饭后和小王一起回安吉，在她家住下。阿姨给我买了套睡衣。
1. 初二初三（0130-0131）和小王家的亲戚们吃饭，初三晚上回家。
1. 难得的长假，在家睡觉看书学习，偶尔去拜年吃顿好的，非常舒适。

# 第 06 周（0203-0209）

1. 初六（0203）带上麻麻、姐姐和大外甥去上海接奶奶回家。
1. 初七（0204）去安吉载上小王和建国回杭，高速免费的最后一天，以前不到一小时的路程，开了将近两个小时。
1. 初八（0205）开工，领上开工红包，忙得不可开交，加班到晚上八点。据说开年第一天加班，要加班一年，阿弥陀佛，希望今年少点加班。
1. 周四（0206）管理层团建，从鼓楼出发，最终在太子湾吃饭，将近两万六千步。下午四点散场，去天目里和朋友喝咖啡，一起吃晚饭。
1. 周五（0207）晚上熬了猪油，卤了牛肉。
1. 周六（0208）调休，晚上和小王一起去看《哪吒2》，她订错了电影院，把西溪天街订成了紫荆天街，还好及时发现，开上小白过去，买上饮料和鸡蛋仔，坐下看上两段广告便开始了。
1. 周日（0209）和小王约朋友一起吃虹料理日式自助，酒饱饭足，打包几块未吃完的肉肉喂小区的流浪小猫。

# 第 07 周（0210-0216）

1. 周三（0212）元宵节，提前把情人节（0214）礼物送小王了（实际是因为顺丰太快），是小王心心念念的戴森吹风机嘿嘿。
1. 周四（0213）[入职两周年](../../posts/two-years-at-work/)啦！赶上面向老板的人员聚餐，大伙儿吃到晚上九点，聊得很开心。
1. 周五（0214）晚回家，周六（0215）早上带麻麻去浙二复查 CT，做完回家，晚上返杭。周六小王带建国做了绝育，建国状态还可以。
<!-- 周五，涨薪了 -->
1. 周日（0216）自己在家做中午饭，小王买了安利不沾锅。在晾枕套时不小心掉下去一个，不偏不倚卡在楼层中间，灵机一动，用麻绳挂上几个掰开的回形针勾起来了。下午导师邀请我和小王去她家做做客，之前托宜兴的朋友买了紫砂壶，这次正好带给她。聊完和小王去学校，我理完发，一起吃肯德基，回想之前在学校的日子，不经感慨时间过得快，我们的成长也远在之前的预料之外。

# 第 08 周（0217-0223）

1. 周一周二（0217-0218）中科大来访接待，吃两顿饭，喝一顿黄酒。
1. 周二（0218）被邀请出镜拍六条推广视频。
1. 周三（0219）晚上导师的导师[梁老师](https://baike.baidu.com/item/%E6%A2%81%E4%B8%AD%E5%A0%82/8043654)来杭，导师喊我一起吃饭。之前帮助梁老师把他的文章做成网页，他说很开心，我帮助他「开辟了新的战场」，特地敬了我两次酒，我觉得很荣幸。小王下班了也赶过来，我们一起敬梁老师，敬导师师娘。吃完结束，和小王一起穿雨衣开驴驴回家。晚上十点，老板发现有位开发工程师一人加班上线要到凌晨，让我给他点外卖，作为公司对坚守者的照顾，KFC 安排。
1. 周五（0221）晚上和朋友一起在学校门口吃饭聊天，吃完散步居然遇到大学室友，他正好领导调任前聚餐结束。我们一起在路边聊了一个多小时，从工作讲到家庭，讲到今年及未来发展规划，我们都有美好的未来。
1. 周六（0222）上午和小王一起回安吉，叔叔阿姨准备了丰盛的菜。吃完健康管理员培训，这次我开小白载着阿姨和小王去培训教室。晚上阿姨说要回趟工作室，我把钥匙给她，和她说了下档位、灯光这些，她调了下座椅便出发了。后来小王和我说，阿姨和她说，她开自己的 SUV 开习惯了，开我们的车感觉像在地上爬，笑鼠。
1. 周日（0223）早上，上海工作、很久没见的大学同学问我中午方不方便，原来他来杭州看看母校，见见老师，中午把导师约出来了，让我一起去吃饭。我看时间来得及，和叔叔阿姨说下情况，开着小白回杭州，顺便把宜兴朋友带的第二把紫砂壶送给导师。饭局上，同学分享他在上海事业编的工作经历，讲他两年来的成长，我们一起感谢导师和师娘在大学时期给我们的指引和照顾。饭局结束，同学回上海，我送导师和师娘回家，然后再回安吉。晚上，叔叔烧菜，拿出小王姐姐从西班牙带来的火腿，好吃好吃，吃完返杭，带建国去拆线。医生说建国伤口还没完全愈合，让它不要剧烈运动。这孩子跟哪吒似的，谁管得住呢！ <!-- 文凯、许弘毅 -->

# 第 09 周（0224-0302）

1. 周一（0224）市场 VP 第一次开周会，从九点开到下午两点，强度大大滴。
1. 周二（0225）和老板去上海财大交流合作，下午拜访客户一位。
1. 周四（0227）和老板去中科大交流合作，对方安排很周到，见了学院院长，从吃饭和交流中见识到院士级别人物的眼光。下午在校园参观，特意去少年班逛了一圈，然后继续谈合作。晚餐丰盛，喝了几杯红酒、一瓶啤酒，赶上回家的高铁，到家已将近零点。
1. 本周继续推动公司内宣素材收集、CRM 质检。另外，因为绩效制度调整，内部系统还未迭代，协助项目部临时处理一些客户数据。
1. 周五（0228）大学室友说要拔智齿，给他推荐了雷医生，挑当天不排队的时间去拔掉了。
1. 周六（0301）出车啦！天气回暖，2025 年第一次骑行。晚上线上分享我常用的工具，以 [Logseq](https://logseq.com/) 为主。
1. 周日（0302）在家大搞卫生，做饭，看书。帮大学同学制作了一个 Shiny 应用帮助其在工作中高效处理考勤数据。

# 第 10 周（0303-0309）

1. 本周预订餐厅和茶室五六次。中科大的同学们来公司学习，俺做好对接和接待。
1. 本周协助项目部处理客户数据，第二天产品经理给我点了奈雪，真是客气，和小伙伴们一起分了分。
1. 周四（0306）销售 VP 助理到岗，俺带她并交接市场部分的工作。
1. 周六（0308）和同事去百丈平天堂森林古道徒步，全程四小时左右，最高爬升八百多米，还有野路，有点强度；同事说我的车技不错。早上先送小王去西站，她去上海染发，晚上去西站接她回家。 <!-- 包林、飞雨-->
1. 周日（0309）在家煎牛排，尝试了蟹黄咸蛋黄土豆丝，味道都不错。

# 第 11 周（0310-0316）

1. 本周应酬多多：周一晚上老板带着我和研究院院长吃饭，根据吃饭时讲到的事项推进后续工作，包括内部招聘、外部对接。周二晚上和公司一位总监一起，与投资顾问和中科大同学吃烧烤喝酒到凌晨。周四中午老板和中科大同学吃饭，俺也一起；晚上老部门聚餐邀请俺参加，荣幸之至。
1. 根据年初定的战略，本周召开了绩效会议，同步会议纪要。
1. 老板参加新人座谈会，收集了新人的反馈，其中五条由我跟进落实，下周继续跟进。
1. 对接上海财大合作事项，目前在走合同。
1. 周四（0313）一位学妹在学院老师的提示下向我讲述她目前面临的困惑，认真回复一千多字，她过了很久说我拉了她一把，希望对她有所帮助。 <!-- 马同学，洪老师-->
1. 周五（0314）晚上回家，周六（0315）在家休息，晚上返杭。周日（0316）看书学习、做饭，晚上吃好晚饭和小王去逛城西银泰，在海澜之家买衣服。

# 第 12 周（0317-0323）

1. 本周和 VP 去江苏常熟出差一天半，对方提供酒店住宿。饭局上和领导、教授们喝酒、介绍公司和产品，几位领导看我年轻，问起我年龄。
1. 对研发中心工时情况进行分析，待老板过目反馈。
1. 周五（0321）全公司西湖徒步十公里，通过朋友转介绍找到一日户外运动险，行政很利索地采购了。作为机动人员，备了四根登山杖供徒步吃力的小伙伴使用，不到三分之一的路程便全部分配出去了。中途老板打电话问起我是否有携带物资，调头回去给他们补给，他说我是百宝箱。中午吃完烧烤，休息一会儿，出发回家。到家和老爸一起给门口[装监控](../../posts/home-camera)，现在随时都能看到家外面的情况啦！
1. 周六（0322）早上奶奶和麻麻准备了家里的菜心、地瓜等小菜，到杭州载上小王去安吉，周日（0323）晚回家。

# 第 13 周（0324-0330）

1. 小白后备箱近期不太灵光，周一（0324）下班自己动手更换后备箱锁块，撬开后备箱卡扣发现锁块居然是用内十二角梅花螺丝固定的。无奈下单工具，周四（0327）晚上到货后更换成功，目前使用正常。
1. 周二（0325）休年假，在家看书，下午突发奇想去学校理发。买了水果去看宿舍阿姨，被告知她在休息，便不打扰，留下水果去教学楼走走，发现经济学的很多课程都不在原来教室上课了。买上留夫鸭作为晚上和小王的下饭菜便回家，路上宿舍阿姨发来微信语音，温柔「责备」我没有喊她，问我近况，让我下次再去。晚上，导师也「责备」我今天去学校没有告知他，原来今天梁老师也在，就这样错过了。后面见面机会还会多多哒！
1. 分析 CRM 操作日志，查找一些信息。  <!--客户信息泄露-->
1. 周六（0329）和老板去省人民大会堂参加浙商经济年会，见到很多浙商企业家，听了关于低空经济、人工智能等方面的分享，晚宴抽到奖品，沾沾好运。参加这次年会，很受鼓舞，浙商勇立潮头，作为浙江人，俺啥时候也能撑起一小片天呀。
1. 周日（0330）在家看书，下午开小白把大奖牌放到公司（驴驴载不动大奖牌），和小王在天街吃饭，稍微逛了下。

# 第 14 周（0331-0406）

1. 本周工作照常，另外催一份合同，拍四条推广视频。
1. 周三（0402）收到朋友的报喜，考研顺利上岸，祝福。
1. 本周清明假期，周四（0403）晚送小王和建国回安吉，吃了顿夜宵。
1. 周五（0404）早上回家，下午和爸爸、姑姑去上坟，晚上和麻麻、姐姐姐夫在外婆家吃晚饭。
1. 周六（0405）早上载麻麻、舅妈去看望一位刚生育的亲戚，上午洗车车。
1. 周日（0406）和姐姐带奶奶去医院检查眼睛，初步诊断为老年性白内障，需要手术治疗。中午吃好饭休息一会儿，出发去安吉接小王回杭州，出发前奶奶和我说不用担心。高速免费的最后一天，路上车很多，尤其是安吉回杭州，原本不到一小时的路程，硬是开了两个多小时。

# 第 15 周（0407-0413）

1. 这周开始晚上做一些力量训练，增肌增肥。
1. 室友考研上岸，周四（0410）邀请导师和朋友吃饭，下血本了他，俺也蹭个饭，帮忙说两句话。  <!-- 吃完转了五百大洋给他 -->
1. 周末公司搬新家，入职后第二次搬家，办公环境越来越好啦！

# 第 16 周（0414-0420）

1. 公司新场地[体验](../../posts/company-relocation/)一周，周一（0414）办了乔迁宴，和给力的搬家小伙伴们一起聚餐。
1. 周四（0417）晚下班去小王家，她的澳洲行结束，周五（0418）载她回杭州。
1. 周末家里蹲，好好休息了两天。

# 第 17 周（0421-0427）

1. 忙碌的一周，接到产品框架梳理的工作，花不少时间绘制产品框架图，初步得到肯定，后续讨论完善细化的工作还不少。
1. 临危受命，买茅台、和老板接待、送对方回家。
1. 周边人事变动，跟几位刚入职场的伙伴们谈谈心、打打气。
1. 周六（0426）早上去小王家，在陈兄一家工作之余聊聊天，晚上回杭州路上车非常少，43 分钟就回杭了。想起清明节最后一天开了三个多小时，这次长教训，五一最后一天避开大部队。

# 第 18 周（0428-0504）

1. 工作上越来越忙碌，承担越来越多的内容，拥有钉钉全部权限的管理员给到我了。
1. 周三（0430）和小王四周年啦！晚上在西溪湿地下馆子，把小王从澳洲射箭得奖得来的红酒干了。
1. 五一假期，和认识十一年的高中同学一起吃饭（0503），这次被她抢先买了单。在家休息的日子真舒服呀！

# 第 19 周（0505-0511）

1. 五一最后一天（0505）带了家里的菜去小王家，叔叔准备了丰盛的晚餐。
1. 周二（0506）一大早返杭。到家收拾完出发去上班，小王说建国不见了，翻箱倒柜都没见着，真担心有没有从楼上掉下去，中午回家一趟，发现在床上呼呼大睡，估计是回来路上累着了。
1. 工作日又忙疯啦！
1. 周六（0510）和小王一起参加博主数字生命卡兹克组织的[「一起 AI，交个朋友」](https://mp.weixin.qq.com/s/HiOOXbkSxX6EjvkMGlHWpQ)活动，有趣的是活动用 O3 进行分组，还把我和小王分到了一组。参加活动见识到大伙儿在用 AI 做什么，也遇到了科技大牛。晚餐和小王的小伙伴们一起干饭，这天的停车费由小王包圆了。
1. 周日（0511）是母亲节呀，早上从盒马买鲜花和一些烘焙食品，到了之后就开上小白粗发，给麻麻一个大惊喜嘿嘿！老爸抓了新鲜的龙虾和小鱼，麻麻去地里翻土豆（现在土豆还没完全长开，一个个挺小吃起来怪奢侈的），中午美美饱餐一顿，打包带回杭州，让小王也享福下。

# 第 20 周（0512-0518）

1. 发起公司满意度调查，并做统计分析，画了热力图，发现还是 ggplot2 好使。
1. 为了解公司层面会议情况，统计四月至今的日程，用了 OCR 和数据处理。
1. 周六（0517）去参加软姐的婚礼啦！晚上和小王粑粑麻麻吃了阿琴烧烤。
1. 周日（0518）去给俺的 47 牙做根管填充啦，小疼。后面就是牙冠，再去两次雷医生那边就差不多了。

# 第 21 周（0519-0525）

1. 公司战略复盘，市场中心内部先做研讨，梳理问题框架和会议要点。
1. 本周又有较大的人事变动，和老板一起顶住压力，把这一阵平稳过去。
1. 周六（0524）加班一天，调整组织架构和审批流程。晚上去学校和学妹（LC）聊聊天，之前听导师讲起过，这次第一次见面，很合得来。结束去接送小王和她的大学室友们回家。
1. 周日（0525）去给 47 牙做桩备啦，雷医生吭哧吭哧搞了一个多小时，折腾坏了。下午去老师家做客聊聊天，和她溜了溜狗狗。晚饭带着小王和优秀学妹认识下，在欧美金融城吃小烧烤，很投机，后面一起搞事业。

# 第 22 周（0526-0601）

1. 五月忙忙碌碌，平均工时 13.1。
1. 新一年的租房合同和停车缴费，小王和房东重新谈了房租，每月降 430。
1. 周六（0531）小王麻麻组局吃饭。

# 第 23 周（0602-0608）

1. 最近工作围绕如何让需求的收集、流转、承接、完成链路更高效开展。
1. 砍价、走合同，买了两箱茅台原箱，送到北京公司。
1. 47 牙的牙冠终于戴上了，经历了将近九个月的治疗，收尾！

# 第 24 周（0609-0615）

1. 周一（0609）晚上和老板接待高校同学。
1. 给老板预订济南餐厅，客户说山东人热情好客，让我们请客不存在的。当天老板给我发消息「诗涛，把账结清下，他们不让我结账」，给俺笑坏了。俺线上结好后，不知道他最后是怎么脱身的。
1. 本周完成质检清单的梳理，用 Shiny 搭建的质检看板已完成考勤模块，原始数据到结果的计算在本地完成，结果推送到看板进行展示。后续将逐步获取授权，将更多零散数据整理收录到看板中。
1. 周五（0613）和中科大博士朋友吃晚饭告别，相遇即是缘。晚上收拾东西回家开上小白回家。
1. 周六（0614）在家休息，看一些管理类的文章，产生几个想法，可以自己先推动尝试。下午和姐姐一起去外婆家逛逛。
1. 老板约了几位小伙伴周日（0615）下午去萧山摘杨梅，风雨无阻。上午送粑粑来浙一检查，路上雨很大。送到后接同事去萧山，和大伙儿一起穿着雨衣上高山，爬树摘杨梅，有趣极了。

# 第 25 周（0616-0622）

1. 申请数据权限，完善看板中的各个模板，系统的数据有很多细节的地方需要核对。
1. 周二（0617）学妹（LC）说遇到工作和生活上的小问题，晚上在天目里和小王三个人一起吃饭聊天，她说解开了。本周她毕业，同为总助，签三年劳动合同，成为有车一族。
1. 周五（0620）粑粑来浙一庆春院区住院，做个小手术，周六（0621）白天陪床，周日（0622）载粑粑回家。

# 第 26 周（0623-0629）

1. 中途参与前期没有参加过的价格策略讨论，费老大劲搞明白内容并做会议纪要，跟踪参与后续价格策略讨论。
1. 和新入职的小伙伴聊了聊，发现其中一位对自己的 KPI 有些不满，甚至有离职倾向。细聊下来她对公司还是很满意的，于是以闲聊的形式向她的 +2 反馈了下，目前有向好发展。
1. 参加公司人才画像研讨会，还挺有意思。
1. 第三期新人培训，做满意度调查并反馈相关部门。
1. 周五（0527）下班后去西站接小王去俺家，小外甥一周岁啦！周六（0528）上午在家布置场地，搞了周岁仪式（简单说就是拍照），晚上亲戚朋友一起吃吃喝喝，散场后回家把小王从上海带来的蛋糕切了，吃完我们便返杭啦！
1. 纠结两个星期后，下单了 3.8L 的 itx 小主机，AMD 8700G，小王赞助了一把，在此鸣谢。
1. 周日（0629）去学校，拍摄十佳大学生的采访视频，请拍摄的同学们喝了星巴克。拍完理个发，回家。

# 第 27 周（0630-0706）

1. 本周布置半年度复盘任务，半年度最后一天业绩冲刺很不错，周二（0701）给市场管理的小伙伴们点了星巴克。
1. 和老板讨论质检看板的改进，主要是增加同环比和日期区间选择功能，本以为会比较麻烦，结果本想调研方案的时间用 GPT 直接改好了，用时 2.5 小时。后续就是梳理其他内容并新增板块。
1. 周五（0704）和小王回安吉，周六（0705）和小王麻麻一起去张家港，两百多公里的路程，开她麻麻的车，也是俺第一次开 SUV。在张家港看小王麻麻和她的伙伴做市场，还和陈兄见了一面。
1. 周日（0707）吃好午饭回安吉，再回杭州。稍作休息准备去和 LP、XC、ZY、LC 吃晚饭，发现小王在楼道里鬼鬼祟祟等电梯，没想到是给我的生日蛋糕，太惊喜，自己都忘记的生日小王居然记得，粑粑麻麻也给俺发了红包！说回吃饭，这次我和小王组局，他们以为是要公布什么重大信息，还把给我们准备的订婚礼物提前带来了，我和小王异口同声：「下次来也不能空着手喔」。吃完回家已十点，汇总市场业绩情况，做两个市场激励方案已过零点，发给老板后倒头睡辽。

# 第 28 周（0707-0713）

1. 这周时而晴天时而暴雨，周五（0711）中午和饭搭子出去吃饭，刚吃上就暴雨，最后打车回公司，全程 200 米，司机师傅估计都乐开花了。
1. 周六（0712）上午和小王回家一起吃午饭。下午去安吉，接待张家港来玩的小伙伴。吃上了去小王外婆家拿的卤鸭。
1. 周日（0713）去安吉山间小溪乘凉聊天，在农家乐吃午饭。来安吉旅游度假的人真多，大部分都是江浙沪的车牌。

# 第 29 周（0714-0720）

1. 在 WSL 里边装好 Claude Code，然后用 Kimi K2 驱动，再结合 MCP，感觉离智能更近了一步。
1. 拆开小主机理下线，发现电源居然接了两根多余的线，搞得散热空间少很多。拆掉之后干净多了，跑下分还能多三万。
1. 周末两天，陪小王练车，总计 70 公里，再多练一练，尤其是变道和倒车，以后俺也可以美滋滋坐副驾咯。

# 第 30 周（0721-0727）

1. 周二（0722）午饭搭子离职，是他一年多来心心念念的结果。周末带他去安吉溜达溜达散散心，听了两天陈兄的健康管理课程（本想听一天课，徒步一天，但他对健康方面很感兴趣），徒步就下次再安排咯！
1. 我开玩笑地说「饭搭子的离职不是一时的暴雨，而是一生的潮湿。」这两月我的午饭和晚饭搭子们都离职了，偶尔也有小伙伴一起吃饭，但更多回到独自一人的状态。想起大学时有一段独自干饭的时光，有些似曾相识。

# 第 31 周（0728-0803）

1. 入职一个新助理，带一带，看看后续发展咋样。
1. 质检看板搭建差不多啦，全程用时两个月，很多都是大模型帮忙写的，后面根据实际工作开展再添加模块。
1. 周四（0731）中午去午饭搭子家蹭饭啦！他特地多加一个菜，丰盛！
1. 周六（0802）和午饭搭子去算法大佬家做客，他买了沙包放在家，让我们去打拳，也见识了他媳妇儿的厨艺。饭后去商场里体验射箭，结果第二天肩膀酸，有点缺乏锻炼啦！
1. 周日（0803）和小王回安吉，结果小白电瓶没电！用保险的道路救援，搭上电开到安吉，找小叔叔摇人换电瓶，非常利索。

# 第 32 周（0804-0810）

1. 周一（0804）老板正式通知将日程安排工作给到新助理，我在大群和主管群吆喝一声，就变成带他排日程咯！
1. 本周给老板草拟一个对外文件、一个内部培训文件，在 ChatGPT 的帮助下进度很快。
1. 联动推广和研发中心，加快项目上线。
1. 在老板应酬期间，和财务商定在这家经常接待客户的餐厅充值（充 10000 送 2000，还送特色烤鸭券和东坡肉券各 5 张，原本是 2 张，谈判一下变 5 张），属于小小的先斩后奏了。第二天和老板说明下，报销他批老快了。
1. 开小白去出差啦！主要是看下机房，讨论后续的算力需求和合作。
1. 大半年没骑车，周六（0809）打上气、擦擦车，给手电、码表、尾灯、变速器充好电，晚上去西湖溜达一圈。
1. 在李继刚的周报里看到《精神分析如何改变人》，俺也来学习下，估计下周就能看完。































